language: python
python:
- '3.5'
- '3.6'
- '3.7'
- '3.8'
install:
- pip install coverage coveralls
- python bootstrap.py
- "./bin/buildout"
script:
- coverage erase
- coverage run ./bin/test
- coveralls
deploy:
  provider: pypi
  on:
    tags: true
  user: __token__
  password:
    secure: ZNlglgAeZ6GvnZDKOuuvufz0UPNcjHi7NLYIV1X6YE0VGLJ905uKryi5qATdg1qABrxUDTVq2oekWOG6Ba4DW/MUfsi9bavzfXZ3XV7ITZyMneR0agdU+T2gplOOD/O1fEIEqbdlgfKZzAlmDMIge3df92mTjdwrcRiW3QOe3FrMDEFbP7jO45I6oRM38vAS2mQsyeC+LPu6W/BWamQPVbUphHoBy+okubHzKz5fZ8eJmtgZ2BF0YCcb8yNwCk1XADdBYq4xyjKgZfCGc3Jd1zbQ3Of1LCWPLpa8IrPQIrGEdEAD7tUe0WqhMYpNFr8YrSBT4SbyICoe26fNo7O1jeMq2hJ57HgjRnkO/lA6gKX2GqrWFgfhb7tlIRV/bfG5UVeBwG1FHu4jJe1IZLG80BGQip+bVLOrqDRTUqPFv6Nd1Ol5xNonHIOQMfeO3THcdpG0o6SmOmVtsVtWUHJRCVT5nVaKw+kJw8NXhgalYN+t+iXm1mZSqOQOngjZaYG8GFShdWi1XenmkRIUsoW9Y23RgW/NVobJ1om9Kx3iwQsOTmrEV8Bh9WrHRWKrQOcsMBY6vLoQRgEd9txi1fwfj0vjVxXRQE1gkvIyPLOa5higrvjQIdgn1e3yVQgTEm/tt9wqMgXNZwLF/N0Nl30o1DJsqR27cu87/KJ+F9+dRb4=
  distributions: sdist bdist_egg bdist_wheel
  skip_existing: true
